# -*- coding: utf-8 -*-

# Form implementation generated from reading src file 'client.src'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# manual changes
import cv2
import qimage2ndarray



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 328)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.clientsListView = QtWidgets.QListView(self.centralwidget)
        self.clientsListView.setGeometry(QtCore.QRect(350, 31, 201, 191))
        self.clientsListView.setObjectName("clientsListView")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(350, 230, 101, 21))
        self.updateButton.setObjectName("updateButton")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(460, 230, 91, 21))
        self.connectButton.setObjectName("connectButton")
        self.cipherBox = QtWidgets.QComboBox(self.centralwidget)
        self.cipherBox.setGeometry(QtCore.QRect(460, 260, 91, 21))
        self.cipherBox.setObjectName("cipherBox")
        self.cipherBox.addItem("")
        self.cipherBox.addItem("")
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(34, 29, 271, 191))
        self.videoLabel.setText("")
        self.videoLabel.setObjectName("videoLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # manual changes

        self.camera = cv2.VideoCapture(1)
        self.fps = 30
        self.timer = QtCore.QTimer()
        self.video_size = QtCore.QSize(self.videoLabel.geometry().width(), self.videoLabel.geometry().height())
        self.setup_camera(self.fps)

    def setup_camera(self, fps):
        self.camera.set(3, self.video_size.width())
        self.camera.set(4, self.video_size.height())

        self.timer.timeout.connect(self.display_video_stream)
        self.timer.start(int(1000 / self.fps))

    def display_video_stream(self):
        ret, frame = self.camera.read()

        if not ret:
            return False

        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frame = cv2.flip(frame, 1)
        image = qimage2ndarray.array2qimage(frame)

        self.videoLabel.setPixmap(QtGui.QPixmap.fromImage(image))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.cipherBox.setItemText(0, _translate("MainWindow", "Public key exchange"))
        self.cipherBox.setItemText(1, _translate("MainWindow", "Diffie-Hellman"))
